function cstrFieldNames = fieldnames(oStack) %#ok<INUSD>

% fieldnames - METHOD Define field names for focus stack channels

cstrFieldNames = {'bWritable', 'cstrFilenames', 'mfFrameShifts', 'tFrameDuration', ...
                  'fZStep', 'fPixelsPerUM', 'tBlankTime', 'vfBlackTrace', 'bSubtractBlack', 'bConvertToDFF', ...
                  'vnStimulusIDs', 'cvnSequenceIDs', ...                            % - Dynamic properties
                  'vtStimulusDurations', 'vtStimulusStartTimes', 'vtStimulusEndTimes', ...
                  'LowByteChannel', 'HighByteChannel', ...                          % - Dynamic data-returning methods
                  'RawStack', 'AlignedStack', 'SummedFrames', 'SummedAlignedFrames', 'MeanPixels', ...
                  'BlankFrames', 'FrameStimulusInfo'};
